/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.jogovelha.view;

import java.awt.Component;
import java.util.*;

/**
 *
 * @author jai_m
 */
public class TelaJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        resetar.setVisible(false);
        int index = 0;
        for (int i = 0; i < 9; i++) {
            switch (i) {
                case 0 -> {
                    padroesVencedor.add(new ArrayList<>());
                }
                case 3 -> {
                    padroesVencedor.add(new ArrayList<>());
                    index++;
                }
                case 6 -> {
                    padroesVencedor.add(new ArrayList<>());
                    index++;
                }
            }
            padroesVencedor.get(index).add(i);
        }
        
        for (int i = 0; i <= 10; i+=3) {
            switch(i) {
                case 0 -> {
                    padroesVencedor.add(new ArrayList<>());
                    index++;
                }
                case 9 -> {
                    i = 1;
                    padroesVencedor.add(new ArrayList<>());
                    index++;
                }
                case 10 -> {
                    i = 2;
                    padroesVencedor.add(new ArrayList<>());
                    index++;
                }
            }
            padroesVencedor.get(index).add(i);
        }
        
        padroesVencedor.add(new ArrayList<>());
        index++;
        padroesVencedor.get(index).add(0);
        padroesVencedor.get(index).add(4);
        padroesVencedor.get(index).add(8);
        
        padroesVencedor.add(new ArrayList<>());
        index++;
        padroesVencedor.get(index).add(6);
        padroesVencedor.get(index).add(4);
        padroesVencedor.get(index).add(2);
    }
    
    private Map<Integer, String> jogo = new HashMap<>();
    private List<Map.Entry<Integer, String>> jogoList;
    private ArrayList<ArrayList<Integer>> padroesVencedor = new ArrayList();
    
    private void adicionarItemJogo(javax.swing.JComboBox<String> opcao) {
        String itemAtual = opcao.getSelectedItem().toString();
        if (itemAtual.trim().equals("")) {
            return;
        }
        int index = itemsJogo.getComponentZOrder(opcao);
        opcao.setEnabled(false);
        verificarJogo(itemAtual, index);
    }
    
    private void verificarJogo(String itemAtual, int index) {
        jogo.put(index, itemAtual);
        Set<Map.Entry<Integer, String>> jogoSet = jogo.entrySet();
        jogoList = new ArrayList<>(jogoSet);
        if (jogoList.size() >= 5) {
            ArrayList<Integer> posicoes = new ArrayList<>();
            for (int i = 0; i < jogoList.size(); i++) {
                if (jogoList.get(i).getValue().equals(itemAtual)) {
                    posicoes.add(jogoList.get(i).getKey());
                }
            }
            
            for (ArrayList<Integer> padraoVencedor : padroesVencedor) {
                if (posicoes.containsAll(padraoVencedor)) {
                    finalizarPartida(itemAtual);
                    return;
                }
            }
            
            if (jogoList.size() == 9) {
                finalizarPartida("Empate");
            }
         }
        
        
    }
    
    private void finalizarPartida(String vencedor) {
        resultado.setText(vencedor);
        for (int i = 0; i < 9; i++) {
            itemsJogo.getComponent(i).setEnabled(false);
        }
        resetar.setVisible(true);
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        itemsJogo = new javax.swing.JPanel();
        opcoes1 = new javax.swing.JComboBox<>();
        opcoes2 = new javax.swing.JComboBox<>();
        opcoes3 = new javax.swing.JComboBox<>();
        opcoes4 = new javax.swing.JComboBox<>();
        opcoes5 = new javax.swing.JComboBox<>();
        opcoes6 = new javax.swing.JComboBox<>();
        opcoes7 = new javax.swing.JComboBox<>();
        opcoes8 = new javax.swing.JComboBox<>();
        opcoes9 = new javax.swing.JComboBox<>();
        resetar = new javax.swing.JButton();

        jCheckBox2.setText("jCheckBox2");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogo da Velha"));

        jLabel1.setText("Vencedor das Partidas: ");

        resultado.setEditable(false);
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });

        opcoes1.setMaximumRowCount(3);
        opcoes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "X", "0" }));
        opcoes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoes1ActionPerformed(evt);
            }
        });

        opcoes2.setMaximumRowCount(3);
        opcoes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "X", "0" }));
        opcoes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoes2ActionPerformed(evt);
            }
        });

        opcoes3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "X", "0" }));
        opcoes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoes3ActionPerformed(evt);
            }
        });

        opcoes4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "X", "0" }));
        opcoes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoes4ActionPerformed(evt);
            }
        });

        opcoes5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "X", "0" }));
        opcoes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoes5ActionPerformed(evt);
            }
        });

        opcoes6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "X", "0" }));
        opcoes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoes6ActionPerformed(evt);
            }
        });

        opcoes7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "X", "0" }));
        opcoes7.setRequestFocusEnabled(false);
        opcoes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoes7ActionPerformed(evt);
            }
        });

        opcoes8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "X", "0" }));
        opcoes8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoes8ActionPerformed(evt);
            }
        });

        opcoes9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "X", "0" }));
        opcoes9.setVerifyInputWhenFocusTarget(false);
        opcoes9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoes9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout itemsJogoLayout = new javax.swing.GroupLayout(itemsJogo);
        itemsJogo.setLayout(itemsJogoLayout);
        itemsJogoLayout.setHorizontalGroup(
            itemsJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemsJogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemsJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcoes1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(itemsJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcoes4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(itemsJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(opcoes7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        itemsJogoLayout.setVerticalGroup(
            itemsJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemsJogoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(itemsJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcoes1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(itemsJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcoes2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(itemsJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcoes3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcoes9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        resetar.setText("Resetar");
        resetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(itemsJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetar)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(itemsJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetar))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoActionPerformed

    private void opcoes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoes1ActionPerformed
       adicionarItemJogo(opcoes1);
    }//GEN-LAST:event_opcoes1ActionPerformed

    private void opcoes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoes2ActionPerformed
       adicionarItemJogo(opcoes2);
    }//GEN-LAST:event_opcoes2ActionPerformed

    private void opcoes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoes3ActionPerformed
       adicionarItemJogo(opcoes3);
    }//GEN-LAST:event_opcoes3ActionPerformed

    private void opcoes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoes5ActionPerformed
       adicionarItemJogo(opcoes5);
    }//GEN-LAST:event_opcoes5ActionPerformed

    private void opcoes8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoes8ActionPerformed
       adicionarItemJogo(opcoes8);
    }//GEN-LAST:event_opcoes8ActionPerformed

    private void opcoes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoes6ActionPerformed
       adicionarItemJogo(opcoes6);
    }//GEN-LAST:event_opcoes6ActionPerformed

    private void opcoes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoes4ActionPerformed
       adicionarItemJogo(opcoes4);
    }//GEN-LAST:event_opcoes4ActionPerformed

    private void resetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarActionPerformed
        jogo = new HashMap<>();
        for (int i = 0; i < 9; i++) {
            itemsJogo.getComponent(i).setEnabled(true);
        }
        
        opcoes1.setSelectedIndex(0);
        opcoes2.setSelectedIndex(0);
        opcoes3.setSelectedIndex(0);
        opcoes4.setSelectedIndex(0);
        opcoes5.setSelectedIndex(0);
        opcoes6.setSelectedIndex(0);
        opcoes7.setSelectedIndex(0);
        opcoes8.setSelectedIndex(0);
        opcoes9.setSelectedIndex(0);
        resultado.setText(" ");
        resetar.setVisible(false);
    }//GEN-LAST:event_resetarActionPerformed

    private void opcoes9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoes9ActionPerformed
       adicionarItemJogo(opcoes9);
       
    }//GEN-LAST:event_opcoes9ActionPerformed

    private void opcoes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoes7ActionPerformed
       adicionarItemJogo(opcoes7);
     
    }//GEN-LAST:event_opcoes7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel itemsJogo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> opcoes1;
    private javax.swing.JComboBox<String> opcoes2;
    private javax.swing.JComboBox<String> opcoes3;
    private javax.swing.JComboBox<String> opcoes4;
    private javax.swing.JComboBox<String> opcoes5;
    private javax.swing.JComboBox<String> opcoes6;
    private javax.swing.JComboBox<String> opcoes7;
    private javax.swing.JComboBox<String> opcoes8;
    private javax.swing.JComboBox<String> opcoes9;
    private javax.swing.JButton resetar;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
